version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_db:
  pgadmin_data:
