CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
